---
TemplateItem: 
  - TemplateName: Metadata
    MapItems:
    - FieldName: PasgeTitle
      MapTo: Title
    - FieldName: Subtitle
      MapTo: Subheading
  - TemplateName: CallToAction2
    MapItems:
    - FieldName: Heading
      MapTo: Title
    - FieldName: Subtitle
      MapTo: Subheading
...